<a href="https://colab.research.google.com/github/marioguerrerosalah/APRENDIZAJE--SUPERVISADO/blob/main/Taller_completo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller 1


Se tiene un conjunto de datos de 1500 registros con las siguientes variables:

- edad_cliente (años)
- tiempo_como_cliente_meses
- ingresos_mensuales (dolares)
- visitas_mensuales_sitio_web
- contactos (call-center)
- nivel_educativo (1:primaria, 2:secundaria, 3:tecnico-tecnologico, 4:universitario, 5 posgrado)
- uso_tarjeta_credito (1: Si, 0: No)
- participa_en_promociones (1: Si, 0: No)
- calificacion_satisfaccion (1-5, donde 1 es muy bajo y 5 es excelente)
- descuento_promedio_usado (%)
- ventas_cliente (Ventas promedio al cliente en dolares)


Se espera que el cientifico de datos presente el mejor modelo de regresión posible para predecir las ventas del cliente, con el respectivo informe ejecutivo para el gerente.
Se deben validar todos los supuestos de la regresión y que esta no presente problemas.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
path= '/content/drive/MyDrive/APREN. SUPERVISADO/dataset_regresion_ventas.csv'
df= pd.read_csv(path)

In [ ]:
df.head()

,edad_cliente,tiempo_como_cliente_meses,ingresos_mensuales,visitas_mensuales_sitio_web,contactos,nivel_educativo,uso_tarjeta_credito,participa_en_promociones,calificacion_satisfaccion,descuento_promedio_usado,ventas_cliente
0,50,62,3450,6,0,4,0,1,4,0.26,371.17
1,49,7,2580,4,3,4,1,1,3,0.21,329.62
2,42,92,3090,6,1,4,0,1,3,0.29,589.01
3,30,119,3000,12,1,2,1,1,4,0.21,476.49
4,40,108,2840,4,1,1,1,0,5,0.00,460.06

# Partición entre entrenamiento y prueba

In [ ]:
train= df.sample(frac=0.7, random_state=42)
test= df.drop(train.index)

In [ ]:
train.head()

,edad_cliente,tiempo_como_cliente_meses,ingresos_mensuales,visitas_mensuales_sitio_web,contactos,nivel_educativo,uso_tarjeta_credito,participa_en_promociones,calificacion_satisfaccion,descuento_promedio_usado,ventas_cliente
1116,62,107,3350,4,2,1,1,1,1,0.14,751.28
1368,49,65,2150,4,1,1,0,1,5,0.13,282.12
422,25,27,1970,8,0,4,0,0,4,0.00,277.81
413,36,61,1620,4,4,2,1,1,4,0.02,441.05
451,40,91,3060,3,2,4,1,1,4,0.18,539.97

**ESTA ES LA MEJOR PARTICION PARA LOS MODELOS**

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop('ventas_cliente', axis=1)
y = df['ventas_cliente']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Para usar las variables de la regresión, estas deben ser tipo array
X = np.array(X_train)
Y = np.array(y_train).reshape(-1, 1)

# Modelo de regresión
modelo = LinearRegression()
modelo.fit(X, Y)

# Ver coeficientes
print("Intercepto (a):", modelo.intercept_)
print("Pendiente (b):", modelo.coef_)

Intercepto (a): [24.35259286]
Pendiente (b): [[ 2.51556660e+00  1.65681969e+00  3.06986683e-02  5.92138273e+00
  -3.24705308e+00  4.39620699e+00  1.53000592e+01  2.76264762e+01
   7.23860782e+00  2.39196751e+02]]

In [ ]:
df_train = pd.concat([y_train, X_train], axis=1)
df_train.head()

,ventas_cliente,edad_cliente,tiempo_como_cliente_meses,ingresos_mensuales,visitas_mensuales_sitio_web,contactos,nivel_educativo,uso_tarjeta_credito,participa_en_promociones,calificacion_satisfaccion,descuento_promedio_usado
485,566.41,69,64,3080,3,0,1,1,1,4,0.13
527,274.19,60,71,2200,2,2,1,1,1,1,0.09
199,638.33,58,106,2480,4,4,2,1,1,3,0.18
889,615.45,24,80,3060,5,1,2,0,1,3,0.14
844,309.97,19,83,1420,4,1,2,1,1,4,0.20

In [ ]:
corr_matrix = df_train.corr()
corr_matrix

,ventas_cliente,edad_cliente,tiempo_como_cliente_meses,ingresos_mensuales,visitas_mensuales_sitio_web,contactos,nivel_educativo,uso_tarjeta_credito,participa_en_promociones,calificacion_satisfaccion,descuento_promedio_usado
ventas_cliente,1.000000,0.333451,0.461898,0.188439,0.092546,-0.005390,0.016679,0.051305,0.215398,0.049487,0.230816
edad_cliente,0.333451,1.000000,0.056677,0.053872,-0.011601,0.000814,0.025017,-0.029220,0.032381,-0.040240,-0.008976
tiempo_como_cliente_meses,0.461898,0.056677,1.000000,-0.030981,-0.036773,0.051261,-0.034918,-0.030263,0.042638,-0.014431,0.018369
ingresos_mensuales,0.188439,0.053872,-0.030981,1.000000,-0.026332,0.014210,0.018459,-0.032677,0.017619,0.015581,0.016038
visitas_mensuales_sitio_web,0.092546,-0.011601,-0.036773,-0.026332,1.000000,-0.002306,-0.032338,0.072076,0.068275,0.040186,0.030081
contactos,-0.005390,0.000814,0.051261,0.014210,-0.002306,1.000000,0.006322,-0.050248,0.036033,-0.058547,0.044986
nivel_educativo,0.016679,0.025017,-0.034918,0.018459,-0.032338,0.006322,1.000000,-0.013248,-0.047816,-0.040406,-0.036272
uso_tarjeta_credito,0.051305,-0.029220,-0.030263,-0.032677,0.072076,-0.050248,-0.013248,1.000000,0.070764,-0.002743,0.031106
participa_en_promociones,0.215398,0.032381,0.042638,0.017619,0.068275,0.036033,-0.047816,0.070764,1.000000,-0.047135,0.559249
calificacion_satisfaccion,0.049487,-0.040240,-0.014431,0.015581,0.040186,-0.058547,-0.040406,-0.002743,-0.047135,1.000000,-0.040850
descuento_promedio_usado,0.230816,-0.008976,0.018369,0.016038,0.030081,0.044986,-0.036272,0.031106,0.559249,-0.040850,1.000000

In [ ]:
import statsmodels.api as sm

# Intercepto
X_const = sm.add_constant(X_train)

# Modelo de regresión
modelo_sm = sm.OLS(y_train, X_const).fit()

# Imprimir el resumen del modelo (incluye la ecuación y ANOVA)
print(modelo_sm.summary())

# Obtener y mostrar los residuales
residuales = modelo_sm.resid
print("\nResiduales:")
print(residuales)

                            OLS Regression Results
==============================================================================
Dep. Variable:         ventas_cliente   R-squared:                       0.420
Model:                            OLS   Adj. R-squared:                  0.415
Method:                 Least Squares   F-statistic:                     75.29
Date:                Thu, 19 Feb 2026   Prob (F-statistic):          1.07e-115
Time:                        14:27:52   Log-Likelihood:                -6285.8
No. Observations:                1050   AIC:                         1.259e+04
Df Residuals:                    1039   BIC:                         1.265e+04
Df Model:                          10
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                          24.3526     22.006      1.107      0.269     -18.829      67.534
edad_cliente                    2.5156      0.198     12.700      0.000       2.127       2.904
tiempo_como_cliente_meses       1.6568      0.087     19.085      0.000       1.486       1.827
ingresos_mensuales              0.0307      0.004      7.815      0.000       0.023       0.038
visitas_mensuales_sitio_web     5.9214      1.397      4.237      0.000       3.179       8.663
contactos                      -3.2471      2.192     -1.481      0.139      -7.549       1.055
nivel_educativo                 4.3962      2.674      1.644      0.100      -0.850       9.643
uso_tarjeta_credito            15.3001      6.021      2.541      0.011       3.485      27.116
participa_en_promociones       27.6265     10.176      2.715      0.007       7.658      47.595
calificacion_satisfaccion       7.2386      2.391      3.028      0.003       2.547      11.930
descuento_promedio_usado      239.1968     37.988      6.297      0.000     164.656     313.738
==============================================================================
Omnibus:                        2.266   Durbin-Watson:                   1.953
Prob(Omnibus):                  0.322   Jarque-Bera (JB):                2.332
Skew:                          -0.099   Prob(JB):                        0.312
Kurtosis:                       2.880   Cond. No.                     4.02e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.02e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Residuales:
485      42.758054
527    -167.705574
199      89.131454
889     186.258189
844     -92.237710
           ...
1130    174.943530
1294    -35.860132
860      -1.346484
1459    170.365060
1126    151.945141
Length: 1050, dtype: float64

## Otras métricas para evaluar el desempeño del modelo

In [ ]:
current_aic = modelo_sm.aic
current_bic = modelo_sm.bic
print("aic:", current_aic)
print("bic:", current_bic)

aic: 12593.623168583585
bic: 12648.145168458252

Tanto el AIC (Akaike Information Criterion) como el BIC (Bayesian Information Criterion) son criterios para comparar modelos estadísticos y elegir el que logra un mejor balance entre ajuste y simplicidad.

- AIC evalúa la calidad global del modelo, penalizando la complejidad.
- BIC suele preferir modelos más simples.

## Modelo de regresión después de haber eliminado la variable ```contactos```

In [ ]:
X_train.drop('contactos', axis=1, inplace=True)
X_const = sm.add_constant(X_train)

# Modelo de regresión
modelo_sm2 = sm.OLS(y_train, X_const).fit()

# Imprimir el resumen del modelo (incluye la ecuación y ANOVA)
print(modelo_sm2.summary())

# Obtener y mostrar los residuales
residuales = modelo_sm2.resid
print("\nResiduales:")
print(residuales)

                            OLS Regression Results
==============================================================================
Dep. Variable:         ventas_cliente   R-squared:                       0.419
Model:                            OLS   Adj. R-squared:                  0.414
Method:                 Least Squares   F-statistic:                     83.31
Date:                Thu, 19 Feb 2026   Prob (F-statistic):          3.37e-116
Time:                        14:40:19   Log-Likelihood:                -6286.9
No. Observations:                1050   AIC:                         1.259e+04
Df Residuals:                    1040   BIC:                         1.264e+04
Df Model:                           9
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                          17.8971     21.583      0.829      0.407     -24.453      60.247
edad_cliente                    2.5176      0.198     12.703      0.000       2.129       2.906
tiempo_como_cliente_meses       1.6505      0.087     19.024      0.000       1.480       1.821
ingresos_mensuales              0.0306      0.004      7.790      0.000       0.023       0.038
visitas_mensuales_sitio_web     5.9134      1.398      4.229      0.000       3.170       8.657
nivel_educativo                 4.3680      2.675      1.633      0.103      -0.882       9.618
uso_tarjeta_credito            15.7540      6.017      2.618      0.009       3.947      27.561
participa_en_promociones       27.4308     10.181      2.694      0.007       7.453      47.409
calificacion_satisfaccion       7.4376      2.388      3.114      0.002       2.751      12.124
descuento_promedio_usado      237.5832     37.994      6.253      0.000     163.030     312.136
==============================================================================
Omnibus:                        2.008   Durbin-Watson:                   1.953
Prob(Omnibus):                  0.366   Jarque-Bera (JB):                2.079
Skew:                          -0.094   Prob(JB):                        0.354
Kurtosis:                       2.889   Cond. No.                     4.02e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.02e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Residuales:
485      48.944051
527    -167.501486
199      82.879968
889     190.098902
844     -89.070255
           ...
1130    181.518408
1294    -32.172772
860      -1.128247
1459    174.474017
1126    155.201981
Length: 1050, dtype: float64

In [ ]:
current_aic2 = modelo_sm2.aic
current_bic2 = modelo_sm2.bic
print("aic:", current_aic)
print("aic2:", current_aic2)
print("bic:", current_bic)
print("bic2:", current_bic2)

aic: 12593.623168583585
aic2: 12593.83749181889
bic: 12648.145168458252
bic2: 12643.402946250404

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop('ventas_cliente', axis=1)
y = df['ventas_cliente']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Mejor modelo con forward selection

In [ ]:
def forward_selection(X_train, y_train):

    selected_features = []
    remaining_features = list(X_train.columns)
    best_aic = float('inf')

    while remaining_features:
        best_new_feature = None
        improved = False

        for feature in remaining_features:
            current_features = selected_features + [feature]
            X_temp = sm.add_constant(X_train[current_features])
            model = sm.OLS(y_train, X_temp).fit()
            current_aic = model.aic

            if current_aic < best_aic:
                best_aic = current_aic
                best_new_feature = feature
                improved = True

        if improved:
            selected_features.append(best_new_feature)
            remaining_features.remove(best_new_feature)
            print(f"Añadiendo {best_new_feature}. Current AIC: {best_aic:.2f}")
        else:
            break

    return selected_features

selected_features_forward = forward_selection(X_train, y_train)
print("\nVariables seleccionadas usando forward selection:", selected_features_forward)

Añadiendo tiempo_como_cliente_meses. Current AIC: 12895.89
Añadiendo edad_cliente. Current AIC: 12763.18
Añadiendo descuento_promedio_usado. Current AIC: 12685.05
Añadiendo ingresos_mensuales. Current AIC: 12631.27
Añadiendo visitas_mensuales_sitio_web. Current AIC: 12611.87
Añadiendo calificacion_satisfaccion. Current AIC: 12605.23
Añadiendo participa_en_promociones. Current AIC: 12599.34
Añadiendo uso_tarjeta_credito. Current AIC: 12594.53
Añadiendo nivel_educativo. Current AIC: 12593.84
Añadiendo contactos. Current AIC: 12593.62

Variables seleccionadas usando forward selection: ['tiempo_como_cliente_meses', 'edad_cliente', 'descuento_promedio_usado', 'ingresos_mensuales', 'visitas_mensuales_sitio_web', 'calificacion_satisfaccion', 'participa_en_promociones', 'uso_tarjeta_credito', 'nivel_educativo', 'contactos']

## Mejor modelo usando backward elimination

In [ ]:
def backward_elimination(X_train, y_train):

    selected_features = list(X_train.columns)
    X_temp_initial = sm.add_constant(X_train[selected_features])
    model_initial = sm.OLS(y_train, X_temp_initial).fit()
    best_aic = model_initial.aic
    print(f"AIC inicial with all features: {best_aic:.2f}")

    while selected_features:
        feature_to_remove = None
        improved = False
        worst_aic = best_aic # Inicializar con el mejor AIC

        for feature in selected_features:
            temp_features = [f for f in selected_features if f != feature]
            if not temp_features:
                 X_temp = pd.DataFrame({'const': np.ones(len(X_train))})
            else:
                X_temp = sm.add_constant(X_train[temp_features])

            model = sm.OLS(y_train, X_temp).fit()
            current_aic = model.aic

            # En backward elimination, se eliminan las variables que no están, cuando se obtuvo el mejor AIC
            if current_aic < best_aic:
                best_aic = current_aic
                feature_to_remove = feature
                improved = True

        if improved:
            selected_features.remove(feature_to_remove)
            print(f"Variables removidas {feature_to_remove}. Nuevo mejor AIC: {best_aic:.2f}")
        else:
            break

    return selected_features

selected_features_backward = backward_elimination(X_train, y_train)
print("\nVariables seleccionadas usando backward elimination:", selected_features_backward)

AIC inicial with all features: 12593.62

Variables seleccionadas usando backward elimination: ['edad_cliente', 'tiempo_como_cliente_meses', 'ingresos_mensuales', 'visitas_mensuales_sitio_web', 'contactos', 'nivel_educativo', 'uso_tarjeta_credito', 'participa_en_promociones', 'calificacion_satisfaccion', 'descuento_promedio_usado']

## Mejor modelo usando stepwise selection

In [ ]:
def stepwise_selection(X_train, y_train):

    selected_features = []
    remaining_features = list(X_train.columns)
    best_aic = float('inf')
    no_improvement_count = 0

    while no_improvement_count < 2: # Continue as long as there is potential for improvement (add or remove)
        added_feature = None
        removed_feature = None

        # Step 1: Attempt to add a feature (Forward step)
        best_new_feature = None
        improved_add = False
        current_best_aic_add = best_aic

        for feature in remaining_features:
            current_features = selected_features + [feature]
            X_temp = sm.add_constant(X_train[current_features])
            # Ensure indices are aligned
            X_temp = X_temp.align(y_train, join='inner', axis=0)[0]
            model = sm.OLS(y_train, X_temp).fit()
            current_aic = model.aic

            if current_aic < current_best_aic_add:
                current_best_aic_add = current_aic
                best_new_feature = feature
                improved_add = True

        if improved_add and current_best_aic_add < best_aic:
            best_aic = current_best_aic_add
            selected_features.append(best_new_feature)
            remaining_features.remove(best_new_feature)
            added_feature = best_new_feature
            print(f"Added {best_new_feature}. Current AIC: {best_aic:.2f}")
            no_improvement_count = 0 # Reset counter if improvement made

        # Step 2: Attempt to remove a feature (Backward step)
        feature_to_remove = None
        improved_remove = False
        current_best_aic_remove = best_aic

        if selected_features: # Only attempt removal if there are selected features
             for feature in selected_features:
                temp_features = [f for f in selected_features if f != feature]
                if not temp_features: # Handle the case where removing the last feature
                    X_temp = pd.DataFrame({'const': np.ones(len(X_train))}, index=X_train.index)
                else:
                    X_temp = sm.add_constant(X_train[temp_features])

                # Ensure indices are aligned
                X_temp = X_temp.align(y_train, join='inner', axis=0)[0]
                model = sm.OLS(y_train, X_temp).fit()
                current_aic = model.aic

                if current_aic < current_best_aic_remove:
                    current_best_aic_remove = current_aic
                    feature_to_remove = feature
                    improved_remove = True

        if improved_remove and current_best_aic_remove < best_aic:
            best_aic = current_best_aic_remove
            remaining_features.append(feature_to_remove)
            selected_features.remove(feature_to_remove)
            removed_feature = feature_to_remove
            print(f"Removed {feature_to_remove}. Current AIC: {best_aic:.2f}")
            no_improvement_count = 0 # Reset counter if improvement made

        # Check for improvement in this iteration
        if added_feature is None and removed_feature is None:
            no_improvement_count += 1
        else:
            no_improvement_count = 0


    return selected_features

selected_features_stepwise = stepwise_selection(X_train, y_train)
print("\nSelected features using stepwise selection:", selected_features_stepwise)

Added tiempo_como_cliente_meses. Current AIC: 12895.89
Added edad_cliente. Current AIC: 12763.18
Added descuento_promedio_usado. Current AIC: 12685.05
Added ingresos_mensuales. Current AIC: 12631.27
Added visitas_mensuales_sitio_web. Current AIC: 12611.87
Added calificacion_satisfaccion. Current AIC: 12605.23
Added participa_en_promociones. Current AIC: 12599.34
Added uso_tarjeta_credito. Current AIC: 12594.53
Added nivel_educativo. Current AIC: 12593.84
Added contactos. Current AIC: 12593.62

Selected features using stepwise selection: ['tiempo_como_cliente_meses', 'edad_cliente', 'descuento_promedio_usado', 'ingresos_mensuales', 'visitas_mensuales_sitio_web', 'calificacion_satisfaccion', 'participa_en_promociones', 'uso_tarjeta_credito', 'nivel_educativo', 'contactos']

In [ ]:
def stepwise_selection(X_train, y_train):
    selected_features = []
    remaining_features = list(X_train.columns)
    best_aic = float('inf')
    no_improvement_count = 0

    while no_improvement_count < 2: # Continue as long as there is potential for improvement (add or remove)
        added_feature = None
        removed_feature = None

        # Step 1: Attempt to add a feature (Forward step)
        best_new_feature = None
        improved_add = False
        current_best_aic_add = best_aic

        for feature in remaining_features:
            current_features = selected_features + [feature]
            X_temp = sm.add_constant(X_train[current_features])
            # Ensure indices are aligned
            X_temp = X_temp.align(y_train, join='inner', axis=0)[0]
            model = sm.OLS(y_train, X_temp).fit()
            current_aic = model.aic

            if current_aic < current_best_aic_add:
                current_best_aic_add = current_aic
                best_new_feature = feature
                improved_add = True

        if improved_add and current_best_aic_add < best_aic:
            best_aic = current_best_aic_add
            selected_features.append(best_new_feature)
            remaining_features.remove(best_new_feature)
            added_feature = best_new_feature
            print(f"Added {best_new_feature}. Current AIC: {best_aic:.2f}")
            no_improvement_count = 0 # Reset counter if improvement made

        # Step 2: Attempt to remove a feature (Backward step)
        feature_to_remove = None
        improved_remove = False
        current_best_aic_remove = best_aic

        if selected_features: # Only attempt removal if there are selected features
             for feature in selected_features:
                temp_features = [f for f in selected_features if f != feature]
                if not temp_features: # Handle the case where removing the last feature
                    X_temp = pd.DataFrame({'const': np.ones(len(X_train))}, index=X_train.index)
                else:
                    X_temp = sm.add_constant(X_train[temp_features])

                # Ensure indices are aligned
                X_temp = X_temp.align(y_train, join='inner', axis=0)[0]
                model = sm.OLS(y_train, X_temp).fit()
                current_aic = model.aic

                if current_aic < current_best_aic_remove:
                    current_best_aic_remove = current_aic
                    feature_to_remove = feature
                    improved_remove = True

        if improved_remove and current_best_aic_remove < best_aic:
            best_aic = current_best_aic_remove
            remaining_features.append(feature_to_remove)
            selected_features.remove(feature_to_remove)
            removed_feature = feature_to_remove
            print(f"Removed {feature_to_remove}. Current AIC: {best_aic:.2f}")
            no_improvement_count = 0 # Reset counter if improvement made

        # Check for improvement in this iteration
        if added_feature is None and removed_feature is None:
            no_improvement_count += 1
        else:
            no_improvement_count = 0


    return selected_features

selected_features_stepwise = stepwise_selection(X_train, y_train)
print("\nSelected features using stepwise selection:", selected_features_stepwise)

Added tiempo_como_cliente_meses. Current AIC: 12895.89
Added edad_cliente. Current AIC: 12763.18
Added descuento_promedio_usado. Current AIC: 12685.05
Added ingresos_mensuales. Current AIC: 12631.27
Added visitas_mensuales_sitio_web. Current AIC: 12611.87
Added calificacion_satisfaccion. Current AIC: 12605.23
Added participa_en_promociones. Current AIC: 12599.34
Added uso_tarjeta_credito. Current AIC: 12594.53
Added nivel_educativo. Current AIC: 12593.84
Added contactos. Current AIC: 12593.62

Selected features using stepwise selection: ['tiempo_como_cliente_meses', 'edad_cliente', 'descuento_promedio_usado', 'ingresos_mensuales', 'visitas_mensuales_sitio_web', 'calificacion_satisfaccion', 'participa_en_promociones', 'uso_tarjeta_credito', 'nivel_educativo', 'contactos']

## Mejor modelo usando ```sklearn SequentialFeatureSelector```

In [ ]:
from sklearn.linear_model import LinearRegression
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.datasets import make_regression
import statsmodels.api as sm

# Modelo base
lr = LinearRegression()

# Forward selection
sfs = SFS(lr,
          k_features='best',   # Puede ser número fijo o 'best'
          forward=True,        # True = forward, False = backward
          floating=False,      # True para stepwise mixto
          scoring='r2',
          cv=5)

sfs = sfs.fit(X_train, y_train)

print("Variables seleccionadas usando SequentialFeatureSelector (Forward):", sfs.k_feature_names_)

# Crear y ajustar el modelo OLS con las variables seleccionadas
X_train_selected = sm.add_constant(X_train[list(sfs.k_feature_names_)])
model_sfs = sm.OLS(y_train, X_train_selected).fit()

# Resumen del modelo OLS
print("\nResumen del modelo OLS con variables seleccionadas por SequentialFeatureSelector:")
print(model_sfs.summary())

Variables seleccionadas usando SequentialFeatureSelector (Forward): ('edad_cliente', 'tiempo_como_cliente_meses', 'ingresos_mensuales', 'visitas_mensuales_sitio_web', 'contactos', 'nivel_educativo', 'uso_tarjeta_credito', 'participa_en_promociones', 'calificacion_satisfaccion', 'descuento_promedio_usado')

Resumen del modelo OLS con variables seleccionadas por SequentialFeatureSelector:
                            OLS Regression Results
==============================================================================
Dep. Variable:         ventas_cliente   R-squared:                       0.420
Model:                            OLS   Adj. R-squared:                  0.415
Method:                 Least Squares   F-statistic:                     75.29
Date:                Thu, 19 Feb 2026   Prob (F-statistic):          1.07e-115
Time:                        14:49:13   Log-Likelihood:                -6285.8
No. Observations:                1050   AIC:                         1.259e+04
Df Residuals:                    1039   BIC:                         1.265e+04
Df Model:                          10
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                          24.3526     22.006      1.107      0.269     -18.829      67.534
edad_cliente                    2.5156      0.198     12.700      0.000       2.127       2.904
tiempo_como_cliente_meses       1.6568      0.087     19.085      0.000       1.486       1.827
ingresos_mensuales              0.0307      0.004      7.815      0.000       0.023       0.038
visitas_mensuales_sitio_web     5.9214      1.397      4.237      0.000       3.179       8.663
contactos                      -3.2471      2.192     -1.481      0.139      -7.549       1.055
nivel_educativo                 4.3962      2.674      1.644      0.100      -0.850       9.643
uso_tarjeta_credito            15.3001      6.021      2.541      0.011       3.485      27.116
participa_en_promociones       27.6265     10.176      2.715      0.007       7.658      47.595
calificacion_satisfaccion       7.2386      2.391      3.028      0.003       2.547      11.930
descuento_promedio_usado      239.1968     37.988      6.297      0.000     164.656     313.738
==============================================================================
Omnibus:                        2.266   Durbin-Watson:                   1.953
Prob(Omnibus):                  0.322   Jarque-Bera (JB):                2.332
Skew:                          -0.099   Prob(JB):                        0.312
Kurtosis:                       2.880   Cond. No.                     4.02e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.02e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
y_train.describe()

count    1050.000000
mean      449.739857
std       126.535173
min        -5.680000
25%       360.242500
50%       449.205000
75%       540.190000
max       827.930000
Name: ventas_cliente, dtype: float64

# Análisis de métricas de desempeño

**RMSE — Root Mean Squared Error**
- Es la raíz del promedio de los errores al cuadrado.
- Penaliza más fuerte los errores grandes (porque se elevan al cuadrado).
- Tiene las mismas unidades que la variable objetivo.
- Más bajo → mejor.
- Útil cuando quieres castigar más los errores grandes.
- Si el RMSE = 103.85, significa que en promedio el modelo se equivoca en sus predicciones en $103.85 (pero con énfasis en errores grandes).

**MAE — Mean Absolute Error**
- Es el promedio de los errores absolutos.
- Penaliza todos los errores por igual.
- Más fácil de interpretar: promedio simple de la magnitud del error.
- Más bajo → mejor.
- Menos sensible a valores atípicos que RMSE.
- Si MAE = 83.33, significa que el modelo se equivos en sus predicciones en promedio $83.33.

**MAPE — Mean Absolute Percentage Error**
- Es el porcentaje promedio de error.
- No depende de las unidades.
- Muy intuitivo para comunicar resultados a gente no técnica.
- Si MAPE = 456%, significa que en promedio el modelo se equivoca un 456% respecto al valor real

  Problemas:
  - No se puede calcular si algún valor de y<sub>i</sub> =0
  - Tiende a inflar el error cuando los valores reales son muy pequeños.

## Evaluando el modelo

Se evalua el modelo prediciendo con los datos de prueba, usando R<sup>2</sup>, R<sup>2</sup> ajustado, RMSE, MAE, MAPE.

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
import statsmodels.api as sm

# Predicciones en el set de prueba con el modelo entrenado con SFS features
X_test_selected = sm.add_constant(X_test[list(sfs.k_feature_names_)])
y_pred = model_sfs.predict(X_test_selected)

# RMSE
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"RMSE: {rmse:.2f}")

# MAE
mae = mean_absolute_error(y_test, y_pred)
print(f"MAE: {mae:.2f}")

# Calculate MAPE
# epsilon para evitar la division por cero
epsilon = 1e-10
mape = np.mean(np.abs((y_test - y_pred) / (y_test + epsilon))) * 100
print(f"MAPE: {mape:.2f}%")

# R2
r2 = r2_score(y_test, y_pred)
print(f"R2: {r2:.2f}")

# R2 ajustado
n = len(y_test) # numero de observaciones
p = X_test_selected.shape[1] - 1 # numero de predictores (excluyendo la constante)
adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)
print(f"R2 ajustado: {adj_r2:.2f}")

RMSE: 103.22
MAE: 83.36
MAPE: 460.65%
R2: 0.45
R2 ajustado: 0.44

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

# Predicciones con el set de prueba usando el modelo de entrenamiento con SFS features
X_test_selected = sm.add_constant(X_test[list(sfs.k_feature_names_)])
y_pred = model_sfs.predict(X_test_selected)

# RMSE
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"RMSE: {rmse:.2f}")

# MAE
mae = mean_absolute_error(y_test, y_pred)
print(f"MAE: {mae:.2f}")

# MAPE
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
print(f"MAPE: {mape:.2f}%")

RMSE: 103.22
MAE: 83.36
MAPE: 460.65%

# Regresión con regularizacion

¿Cuándo conviene regularizar?
- Se usa regularización cuando se presenta alguno de estos casos:
- Muchas variables o p ≥ n (alta dimensión). p= variables, n= número de registros.
- Multicolinealidad (predictoras fuertemente correlacionadas).
- Sobreajuste (alto desempeño en entrenamiento, bajo en validación).
- Coeficientes inestables al re-muestrear o pequeños cambios en datos.
- Predicción es prioridad sobre inferencia estricta (p-values/IC).

## Cómo ver las variables seleccionadas?

**Ridge (L2)**

- Ridge nunca pone coeficientes exactamente en 0, solo los “encoge” hacia 0.
- Por tanto, todas las variables permanecen en el modelo, aunque algunas tengan coeficientes muy pequeños (≈0).
- En Ridge no hay selección de variables real, pero puedes ordenar las variables según la magnitud de los coeficientes para ver cuáles son más relevantes.

**Lasso (L1)**

- Lasso sí puede llevar coeficientes exactamente a 0.
- Las variables con βj=0 son descartadas.
- Las que quedan con βj≠0 son las seleccionadas.
- Aquí la selección es explícita: simplemente miras los coeficientes finales.

**Elastic Net (L1 + L2)**
- Combina Lasso y Ridge:
- Puede poner coeficientes en 0 (como Lasso).
- Pero también mantiene grupos de variables correlacionadas (no las descarta todas).
- Variables seleccionadas: aquellas con βj≠0.

In [ ]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Define the features (X) and target (y) based on the previous SFS selection
X_train_regularized = X_train[list(sfs.k_feature_names_)]
X_test_regularized = X_test[list(sfs.k_feature_names_)]

# Ridge Regression
ridge_model = Ridge(alpha=1.0) # You can tune alpha
ridge_model.fit(X_train_regularized, y_train)
y_pred_ridge = ridge_model.predict(X_test_regularized)

print("--- Ridge Regression ---")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_ridge)):.2f}")
print(f"MAE: {mean_absolute_error(y_test, y_pred_ridge):.2f}")
mape_ridge = np.mean(np.abs((y_test - y_pred_ridge) / (y_test + epsilon))) * 100
print(f"MAPE: {mape_ridge:.2f}%")
print(f"R2: {r2_score(y_test, y_pred_ridge):.2f}")

# Lasso Regression
lasso_model = Lasso(alpha=1.0) # You can tune alpha
lasso_model.fit(X_train_regularized, y_train)
y_pred_lasso = lasso_model.predict(X_test_regularized)

print("\n--- Lasso Regression ---")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_lasso)):.2f}")
print(f"MAE: {mean_absolute_error(y_test, y_pred_lasso):.2f}")
mape_lasso = np.mean(np.abs((y_test - y_pred_lasso) / (y_test + epsilon))) * 100
print(f"MAPE: {mape_lasso:.2f}%")
print(f"R2: {r2_score(y_test, y_pred_lasso):.2f}")

# Elastic Net Regression
elastic_net_model = ElasticNet(alpha=1.0, l1_ratio=0.5) # You can tune alpha and l1_ratio
elastic_net_model.fit(X_train_regularized, y_train)
y_pred_elastic_net = elastic_net_model.predict(X_test_regularized)

print("\n--- Elastic Net Regression ---")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_elastic_net)):.2f}")
print(f"MAE: {mean_absolute_error(y_test, y_pred_elastic_net):.2f}")
mape_elastic_net = np.mean(np.abs((y_test - y_pred_elastic_net) / (y_test + epsilon))) * 100
print(f"MAPE: {mape_elastic_net:.2f}%")
print(f"R2: {r2_score(y_test, y_pred_elastic_net):.2f}")

--- Ridge Regression ---
RMSE: 103.42
MAE: 83.51
MAPE: 461.02%
R2: 0.45

--- Lasso Regression ---
RMSE: 105.09
MAE: 84.84
MAPE: 467.10%
R2: 0.43

--- Elastic Net Regression ---
RMSE: 110.12
MAE: 89.00
MAPE: 517.48%
R2: 0.37

## Coeficientes de cada uno de los modelos de regresión con regularización

In [ ]:
print("\n--- Ridge Regression Coefficients ---")
for feature, coef in zip(X_train_regularized.columns, ridge_model.coef_):
    print(f"{feature}: {coef:.4f}")

print("\n--- Lasso Regression Coefficients ---")
for feature, coef in zip(X_train_regularized.columns, lasso_model.coef_):
    print(f"{feature}: {coef:.4f}")

print("\n--- Elastic Net Regression Coefficients ---")
for feature, coef in zip(X_train_regularized.columns, elastic_net_model.coef_):
    print(f"{feature}: {coef:.4f}")

--- Ridge Regression Coefficients ---
edad_cliente: 2.5102
tiempo_como_cliente_meses: 1.6564
ingresos_mensuales: 0.0307
visitas_mensuales_sitio_web: 5.9133
contactos: -3.1927
nivel_educativo: 4.3616
uso_tarjeta_credito: 15.2083
participa_en_promociones: 32.0478
calificacion_satisfaccion: 7.1964
descuento_promedio_usado: 207.9162

--- Lasso Regression Coefficients ---
edad_cliente: 2.4890
tiempo_como_cliente_meses: 1.6530
ingresos_mensuales: 0.0308
visitas_mensuales_sitio_web: 5.8078
contactos: -2.5101
nivel_educativo: 3.2984
uso_tarjeta_credito: 11.5443
participa_en_promociones: 40.4452
calificacion_satisfaccion: 6.3448
descuento_promedio_usado: 100.7265

--- Elastic Net Regression Coefficients ---
edad_cliente: 2.4898
tiempo_como_cliente_meses: 1.6642
ingresos_mensuales: 0.0312
visitas_mensuales_sitio_web: 5.8722
contactos: -1.9198
nivel_educativo: 2.0402
uso_tarjeta_credito: 5.2035
participa_en_promociones: 11.9194
calificacion_satisfaccion: 4.5291
descuento_promedio_usado: 3.8118

# Arbol de regresion

In [ ]:
import pandas as pd
path= '/content/drive/MyDrive/Aprendizaje Supervisado/Sesion 3/Taller/dataset_regresion_ventas.csv'
df= pd.read_csv(path)

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop('ventas_cliente', axis=1)
y = df['ventas_cliente']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Create and train the Decision Tree Regressor model
tree_model = DecisionTreeRegressor(random_state=42)
tree_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_tree = tree_model.predict(X_test)

# Evaluate the model
print("--- Decision Tree Regression ---")

# RMSE
rmse_tree = np.sqrt(mean_squared_error(y_test, y_pred_tree))
print(f"RMSE: {rmse_tree:.2f}")

# MAE
mae_tree = mean_absolute_error(y_test, y_pred_tree)
print(f"MAE: {mae_tree:.2f}")

# MAPE
# Epsilon to prevent division by zero
epsilon = 1e-10
mape_tree = np.mean(np.abs((y_test - y_pred_tree) / (y_test + epsilon))) * 100
print(f"MAPE: {mape_tree:.2f}%")

# R2
r2_tree = r2_score(y_test, y_pred_tree)
print(f"R2: {r2_tree:.2f}")

# R2 ajustado (requires number of features used)
n_test = len(y_test) # numero de observaciones en el test set
p_tree = X_test.shape[1] # numero de predictores
adj_r2_tree = 1 - (1 - r2_tree) * (n_test - 1) / (n_test - p_tree - 1)
print(f"R2 ajustado: {adj_r2_tree:.2f}")

--- Decision Tree Regression ---
RMSE: 140.40
MAE: 112.96
MAPE: 229.55%
R2: -0.02
R2 ajustado: -0.04